{% set name = "conjure-python-client" %}
{% set version = "1.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1e805a1fcf6d1866781240c1dfbb62b217b496f9e0747b4977cd9878ea259268

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip

  run:
    - python
    - enum34  # [py<34]
    - future
    - requests
    - typing

test:
  imports:
    - conjure_python_client

about:
  home: https://pypi.org/project/conjure-python-client/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Python client and JSON encoders for use with generated Conjure clients'

extra:
  recipe-maintainers:
    - ferozco
    - iamdanfox
    - ahggns
