{% set version = "2.12.0" %}

package:
  name: conjure-python-client
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/conjure-python-client/conjure-python-client-{{ version }}.tar.gz
  sha256: ba8cf4fc9d507b34cca660c60761be84ada58ed69ea4e17679e336b9380242d1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools

  run:
    - python >=3.8
    - requests

test:
  imports:
    - conjure_python_client

about:
  home: https://pypi.org/project/conjure-python-client/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python client and JSON encoders for use with generated Conjure clients

extra:
  recipe-maintainers:
    - johnhany97
    - BenjaminLowry
