{% set version = "1.10.6" %}

package:
  name: conjure-python-client
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/conjure-python-client/conjure-python-client-{{ version }}.tar.gz
  sha256: d5a2cf985bf861565d503f353aa5e1a76d60e377f512f04f480ca32fe14cacb6

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip

  run:
    - python
    - enum34  # [py<34]
    - future
    - requests
    - typing  # [py<=37]

test:
  imports:
    - conjure_python_client

about:
  home: https://pypi.org/project/conjure-python-client/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python client and JSON encoders for use with generated Conjure clients

extra:
  recipe-maintainers:
    - iamdanfox
    - ahggns
    - johnhany97
