{% set version = "3.3.0" %}

package:
  name: conjure-python-client
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/conjure-python-client/conjure_python_client-{{ version }}.tar.gz
  sha256: 786762db398f5d1ceda281ef9e225a2deff8441bc4ab6f70c18683c83bd4975d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools

  run:
    - python >={{ python_min }}
    - requests

test:
  requires:
    - python {{ python_min }}
  imports:
    - conjure_python_client

about:
  home: https://pypi.org/project/conjure-python-client/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python client and JSON encoders for use with generated Conjure clients

extra:
  recipe-maintainers:
    - johnhany97
    - BenjaminLowry
