{% set version = "2.5.0" %}

package:
  name: conjure-python-client
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/conjure-python-client/conjure-python-client-{{ version }}.tar.gz
  sha256: d48cdeeb6fe088f4c13dea0b3b75b091b823afd0b9ba6541f265119c17742f81

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.8
    - pip

  run:
    - python >=3.8
    - requests

test:
  imports:
    - conjure_python_client

about:
  home: https://pypi.org/project/conjure-python-client/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python client and JSON encoders for use with generated Conjure clients

extra:
  recipe-maintainers:
    - iamdanfox
    - ahggns
    - johnhany97
