{% set version = "1.10.1" %}

package:
  name: conjure-python-client
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/conjure-python-client/conjure-python-client-{{ version }}.tar.gz
  sha256: d68f19a391a949756b68f46c0b4978efa96f782dca701b2059b7a22967b5cb17

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip

  run:
    - python
    - enum34  # [py<34]
    - future
    - requests
    - typing  # [py<=37]

test:
  imports:
    - conjure_python_client

about:
  home: https://pypi.org/project/conjure-python-client/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python client and JSON encoders for use with generated Conjure clients

extra:
  recipe-maintainers:
    - ferozco
    - iamdanfox
    - ahggns
